const EDITOR_FILTER_BTN = {
  ORIGINAL_WIDTH: "35%",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  ORIGINAL_DISPLAY: "none",
  CLICKED_WIDTH: "43%",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
  CLICKED_DISPLAY: "block"
}

const ACHIEVEMENT_BTN = {
  ORIGINAL_DISPLAY: "none",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  CLICKED_DISPLAY: "flex",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
}

const NAVBAR_BOX_SHADOW = {
  ORIGINAL: "0px 1px 6px rgba(0, 0, 0, 0.08)",
  CATEGORY_CLICKED: "0px 0px 0px #fff",
};

const CATEGORY_BOX_POSITION = {
  ORIGINAL: "-36vh",
  CLICKED: "14vh",
};

const CATEGORY_SELECT_MODAL = {
  original: "-100vh",
  POPUP: "0px",
}

const CARD_ADD_MODAL = {
  ORIGINAL: "-100vh",
  POPUP: "0px",
};

const KOREA_MONEY_MAX_LENGTH = 9;
const CATEGORY_MODAL_OPEN_BTN_VISITED_TEXT = "카테고리 재탐색";
const TOO_BIG_NUMBER_TEXT = "너무 큰 숫자";
const SPONSOR_CARD_MAXIMUM = 6;

const FILTER_BOX = {
  OPEN: true,
  CLOSE: false,
}

const EDITOR_RECOMMEND_BOX = {
  OPEN: true,
  CLOSE: false,
}

export {
  EDITOR_FILTER_BTN,
  ACHIEVEMENT_BTN,
  NAVBAR_BOX_SHADOW,
  CATEGORY_BOX_POSITION,
  CATEGORY_SELECT_MODAL,
  CARD_ADD_MODAL,
  KOREA_MONEY_MAX_LENGTH,
  CATEGORY_MODAL_OPEN_BTN_VISITED_TEXT,
  TOO_BIG_NUMBER_TEXT,
  SPONSOR_CARD_MAXIMUM,
  FILTER_BOX,
  EDITOR_RECOMMEND_BOX,
};