const EDITOR_FILTER_BTN = {
  ORIGINAL_WIDTH: "35%",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  ORIGINAL_DISPLAY: "none",
  CLICKED_WIDTH: "43%",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
  CLICKED_DISPLAY: "block"
}

const ACHIEVEMENT_BTN = {
  ORIGINAL_DISPLAY: "none",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  CLICKED_DISPLAY: "flex",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
}

export { EDITOR_FILTER_BTN, ACHIEVEMENT_BTN };