const EDITOR_FILTER_BTN = {
  ORIGINAL_WIDTH: "35%",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  ORIGINAL_DISPLAY: "none",
  CLICKED_WIDTH: "43%",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
  CLICKED_DISPLAY: "block"
}

const ACHIEVEMENT_BTN = {
  ORIGINAL_DISPLAY: "none",
  ORIGINAL_BACKGROUNDCOLOR: "#fff",
  CLICKED_DISPLAY: "flex",
  CLICKED_BACKGROUNDCOLOR: "#f2f2f2",
}

const NAVBAR_BOX_SHADOW = {
  ORIGINAL: "0px 1px 6px rgba(0, 0, 0, 0.08)",
  CATEGORY_CLICKED: "0px 0px 0px #fff",
};

const CATEGORY_BOX_POSITION = {
  ORIGINAL: "-36vh",
  CLICKED: "14vh",
};

export {
  EDITOR_FILTER_BTN,
  ACHIEVEMENT_BTN,
  NAVBAR_BOX_SHADOW,
  CATEGORY_BOX_POSITION,
};